The quick sort algorithm for sorting arrays proceeds recursively--it selects an element (the "pivot"), reorders the array to make all the elements less than or equal to the pivot appear first, followed by all the elements greater than the pivot. The two subarrays are then sorted recursively.

Implemented naively quick sort has large run times and deep function calls stacks on arrays with many duplicates because the subarrays may differ greatly in size. One solution is to reorder the array so that all elements less than the pivot appear first, followed by all elements equal to the pivot, followed by all elements greater than the pivot. This is known as Dutch flag partioning, because the Dutch national flag consists of three horizontal bands, each in different color. 

**problem:** write a program that takes an array A and an index i into A, and rearranges the elements such all elements less than A[i] (the pivot) appear first, followed by elements equal to the pivot, followed by elements greater than the pivot

The problem is trivial to solve with O(n) additional space store all the smaller elements, those equal to the pivot and those greater. We can avoid O(n) additional space but O(n^2)

To improve the time complexity, we can make a single pass and move all the elements less than the pivot to the beginning. In the second pass we move larger elements to the end. It's easy to perform each pass in a single iteration, moving out of place elements as soon as they are discovered.

First let's implement the naive solution

In [29]:
def swap(i,j,arr):
    item1=arr[i]
    item2=arr[j]
    arr[j],arr[i]=item1,item2

def dutchFlagPartition(pivot_index,arr):
    pivot=arr[pivot_index]
    
    #move all the smaller elements to the start of the array
    for i in range(len(arr)):
        for j in range(i+1,len(arr)):
            if(arr[j]<pivot):
                swap(i,j,arr)
                print(arr)
                break
    
    #second pass move all the larger elements to the end of array
    for i in range(len(arr)-1,-1,-1):
        for j in range(i-1,-1,-1):
            if(arr[j]>pivot):
                swap(i,j,arr)
                print(arr)
                break
        if(arr[j]<pivot):
            break
        

In [30]:
arr=[6,21,3,4,5,9,20]
dutchFlagPartition(3,arr)

[3, 21, 6, 4, 5, 9, 20]
[3, 21, 6, 4, 5, 20, 9]
[3, 21, 6, 4, 20, 5, 9]
[3, 21, 20, 4, 6, 5, 9]
[3, 21, 4, 20, 6, 5, 9]
[3, 4, 21, 20, 6, 5, 9]


That works but its O(n^2) complexity

The additional space complexity is now O(1) but the time complexity is O(n^2). Intuitively this approach is bad because in the first pass when searching for each additional element smaller than the pivot we start from the beginning. However there is no reason to start from so far back, we can begin from the last loaction we advanced to. To improve time complexity we can make a single pass and move all the elements less than pivot to the begininng, in the second pass we move larger elements to the end, it's easy to perform each pass in a singel iteration, moving out of place elements as soon as they are discovered.

In [45]:
def swap(i,j,arr):
    item1=arr[i]
    item2=arr[j]
    arr[j],arr[i]=item1,item2

def dutchFlagPartitionDoublePass(pivot_index,arr):
    pivot=arr[pivot_index]
    smaller=0
    
    #move all the smaller elements to the beginning of the array
    for i in range(len(arr)):
        if(arr[i]<pivot):
            swap(i,smaller,arr)
            smaller+=1
            
    #move all the larger elements to the end of the array
    larger=len(arr)-1
    for j in range(len(arr)-1,-1,-1):
        if(arr[j]>pivot):
            swap(j,larger,arr)
            larger-=1
        

In [46]:
arr=[6,21,3,4,5,9,20]
dutchFlagPartitionDoublePass(3,arr)
arr

[3, 4, 21, 6, 5, 9, 20]

The algorithm we jsut presented is O(n) and space complexity O(1)

The third algorithm we present now is the same time complexity but performs a single pass. We dothis by maintaining for subarrays: bottom (elements less than the pivot), middle (equal to pivot), unclassified and top (elements greater than the pivot). Initially all elements are unclassified. We iterate and move elements intoone of bottom middle ad top groups accordingly to the relative order between the unclassifed element and the pivot.

Suppose the array is <-3,0,-1,1,1,?,?,?,4,2> where the pivot is 1 and ? is the unclassified element. There are three possible cases for the unclassified element A[5].

It could be less than 1 so for example a[5]=-5. In this case we swap it with the first element that's equal to the pivot. So the array becomes <-3,0,-1,-5,1,1,?,?,4,2>

It could be equal to the pivot in this case the array remains unchanged. 

It could be greater than 1 for example A[5]=6 and in that case we swap it with the farthest right unclassified element. So the array becoms <-3,0,-1,1,1,?,?,6,4,2>

If you notice every time the number of unclassifed elements decreases. 

In [3]:
def swap(i,j,arr):
    item1=arr[i]
    item2=arr[j]
    arr[j],arr[i]=item1,item2


def dutchFlagPartitionSinglePass(pivot_index,arr):
    pivot=arr[pivot_index]
    smaller=0
    equal=0
    larger=len(arr)
    
    """The following invariants must be true during partitioning:
        bottom group: Arr[0: smaller-1]
        middle group: Arr[smaller:equal-1]
        unclassified: Arr[equal:larger-1]
        top group: Arr[larger: A.size()-1]"""
    
    while(equal<larger):
        if(arr[equal]<pivot):
            swap(equal,smaller,arr)
            smaller+=1
            equal+=1
        elif(arr[equal]==pivot):
            equal+=1
        elif(arr[equal]>pivot):
            swap(larger-1,equal,arr)
            larger-=1
            


In [72]:
arr=[6,21,3,4,5,9,20]
dutchFlagPartitionSinglePass(5,arr)
arr

[6, 3, 4, 5, 9, 20, 21]

In [73]:
arr=[2,3,2,2,3,2,3,3]
dutchFlagPartitionSinglePass(1,arr)
arr

[2, 2, 2, 2, 3, 3, 3, 3]

Variant: Assuming that keys take one of three values, reorder the array so that all objects with the same key appear together. The order of the subarrays is not important. 

I think the solutions is to pick the midpoint of the keys. If only two appear choose either and use the single pass partition

In [4]:



def select_pivot(arr):
    dicta={}
    for i in range(len(arr)):
        if arr[i] in dicta.keys():
            continue
        else:
            dicta[arr[i]]=1
        if len(dicta.keys())==3:
            break
    return sorted(dicta.keys())

arr1=np.random.randint(1,4,(100,))
print("before:",arr1)
dutchFlagPartitionSinglePass(select_pivot(arr1)[1],arr1)
print("after: ", arr1)

('before:', array([2, 1, 3, 3, 3, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 3, 2,
       1, 2, 2, 3, 1, 2, 3, 3, 2, 3, 1, 2, 1, 3, 2, 3, 1, 3, 2, 2, 3, 1,
       1, 3, 2, 1, 1, 3, 2, 1, 3, 1, 3, 2, 3, 3, 2, 1, 2, 1, 1, 3, 3, 1,
       3, 2, 3, 1, 1, 1, 2, 2, 3, 2, 2, 2, 2, 3, 2, 2, 3, 2, 2, 1, 1, 2,
       2, 3, 3, 2, 3, 1, 2, 3, 1, 2, 2, 1]))
('after: ', array([2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1,
       2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1,
       1, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1,
       2, 1, 2, 2, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]))


In [97]:
# Function to sort array 
def sort012( a, arr_size): 
    lo = 0
    hi = arr_size - 1
    mid = 0
    while mid <= hi: 
        if a[mid] == 0: 
            a[lo], a[mid] = a[mid], a[lo] 
            lo = lo + 1
            mid = mid + 1
        elif a[mid] == 1: 
            mid = mid + 1
        else: 
            a[mid], a[hi] = a[hi], a[mid]  
            hi = hi - 1
    return a 

arr1=np.random.randint(0,3,(100,))
print("before:",arr1)
sort012(arr1,len(arr1))
print("after: ", arr1)

('before:', array([2, 1, 1, 2, 2, 2, 1, 2, 0, 1, 1, 0, 1, 0, 2, 1, 2, 2, 0, 1, 2, 0,
       0, 2, 2, 2, 2, 2, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 2, 1, 1, 1, 1, 2,
       0, 2, 0, 1, 0, 2, 2, 1, 1, 0, 2, 1, 1, 0, 0, 0, 2, 0, 1, 2, 2, 2,
       2, 1, 0, 1, 1, 0, 2, 2, 2, 2, 1, 0, 1, 1, 0, 0, 2, 2, 2, 1, 1, 2,
       1, 1, 1, 0, 0, 2, 2, 0, 0, 1, 1, 2]))
('after: ', array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]))


In [ ]:
#Dutch partition an array with four distinct keys

In [9]:
arr1=np.random.randint(0,4,(10,))
arr1

array([0, 3, 1, 2, 1, 3, 1, 1, 3, 0])

In [10]:
dutchFlagPartitionSinglePass(8,arr1)
arr1

array([0, 1, 2, 1, 1, 1, 0, 3, 3, 3])

Given an array with four values and then n values, reorder the array so that all objects of the same key appear together. Use O(1) additional space and O(n) additional time.

In [16]:
import numpy as np
def swap(i,j,arr):
    if(i!=j):
        item1=arr[i]
        item2=arr[j]
        arr[j],arr[i]=item1,item2

def BruteForce(num_keys,arr):
    smallest=0
    for i in range(num_keys):
        for j in range(smallest,len(arr)):
            if(arr[j]==i):
                swap(j,smallest,arr)
                smallest+=1

In [1]:
import numpy as np
arr3=np.random.randint(0,4,(10,))
print(arr3)
BruteForce(4,arr3)
arr3

[2 1 1 1 2 3 1 3 1 0]


NameError: name 'BruteForce' is not defined

This has a worst time execution time of O(k*n) where k is the number of distinct keys

Variant given an Array of n objects with boolean valued keys, reorder the array so that objects that have the key apper first. The relative ordering of objects with key true

In [27]:
arr_len=10
arr4=[]
for i in range(arr_len):
    ar1=[np.random.randint(0,100),np.random.randint(0,2)]
    arr4.append(ar1)
arr4=np.array(arr4)
arr4

array([[12,  0],
       [58,  1],
       [77,  1],
       [90,  1],
       [49,  0],
       [19,  1],
       [21,  0],
       [71,  1],
       [76,  1],
       [44,  1]])

In [26]:
def swap_two(i,j,arr):
    if(i!=j):
        item1=np.copy(arr[i])
        item2=np.copy(arr[j])
        arr[i,:]=item2
        arr[j,:]=item1

def order_boolean(arr):
    largest=len(arr)-1
    for i in range(len(arr)-1,-1,-1):
        pair=arr[i]
        pair_bool=pair[1]
        if(pair_bool==1):
            swap_two(i,largest,arr)
            largest-=1
            
        

In [20]:

print(arr4)

swap_two(0,4,arr4)
arr4

[[62  1]
 [ 0  1]
 [60  0]
 [ 2  1]
 [65  0]
 [87  0]
 [95  0]
 [29  1]
 [83  0]
 [22  1]]
-----


array([[65,  0],
       [ 0,  1],
       [60,  0],
       [ 2,  1],
       [62,  1],
       [87,  0],
       [95,  0],
       [29,  1],
       [83,  0],
       [22,  1]])

In [28]:
print(arr4)
print('-----')
order_boolean(arr4)
print(arr4)

[[12  0]
 [58  1]
 [77  1]
 [90  1]
 [49  0]
 [19  1]
 [21  0]
 [71  1]
 [76  1]
 [44  1]]
-----
[[12  0]
 [21  0]
 [49  0]
 [58  1]
 [77  1]
 [90  1]
 [19  1]
 [71  1]
 [76  1]
 [44  1]]


Write a program which takes as input an array of digits encoding a decimal number D and updates the array to represent the array to represent the number D+1. For example, if the input is <1,2,9> then you should update the array to <1,3,0>. Your algorithm shoudl work even if it's implemented on a finite precision machine

**Brute Force Solution:** The brute force solution is to convert the array to the integer increment by 1 and then convert it back to an array. Problem here is that finite precision might not work. 

**Alternate Solution:** Implment this as you learned simple addition. Adding and carrying. Worst case execution of this method is O(n).



In [2]:
def increment_num_array(arr):
    arr_len=len(arr)
    #add 1 to the least significant digit
    #define a carry if needed from the addition
    if(arr[-1]==9):
        carry=1
        arr[-1]=0
    else:
        arr[-1]+=1
        carry=0
    #while we have a carry
    index=len(arr)-2
    while(carry>0 and index>=0):
        curr_val=arr[index]
        if(curr_val==9):
            arr[index]=0
            index-=1
        else:
            arr[index]=curr_val+1
            carry=0
    if(carry==1):
        arr.insert(0,1)
        
        
    

In [5]:
test1=[9,9]
increment_num_array(test1)
test1

[1, 0, 0]

Variant: Write a program which takes as input two strings s and t of bits encoding binary numbers $B_t$ and $B_s$, respectively and returns a new string of bits representing the number of $B_s +B_t$

In [18]:
def add_three_bits(a,b,c):
    res=a+b+c
    #return first value and the second value is the carry
    if(res==3):
        return 1,1
    elif(res==2):
        return 0,1
    elif(res==1):
        return 1,0 
    else:
        return 0,0

def add_bit_arrays(bt,bs):
    #carry for adding the bits
    carry=0
    bt_len=len(bt)
    bs_len=len(bs)
    index=max(bt_len,bs_len)-1
    answer=[]
    for i in range(min(bt_len,bs_len)):
        bt_curr=bt[i]
        bs_curr=bs[i]
        ans_val,carry=add_three_bits(bt_curr,bs_curr,carry)
        answer.insert(0,ans_val)
        index-=1
    #now continue carring but with the larger arr
    if(bt_len>bs_len):
        longer_arr=bt
    elif(bt_len==bs_len):
        if(carry==1):
            answer.insert(0,1)
            return answer
        else:
            return answer
    else:
        longer_arr=bs
        
    while(index>=0):
        ans_val,carry=add_three_bits(carry,longer_arr[index],0)
        answer.insert(0,ans_val)
        index-=1
        
    if(carry==1):
        answer.insert(0,1)
    
    return answer
    
    
        
        
    

In [21]:
b1=[1,0,0,1]
b2=[1,1]
print(add_bit_arrays(b1,b2))

b1=[1,1]
b2=[1,1]
add_bit_arrays(b1,b2)

[1, 1, 0, 0]


[1, 1, 0]

Multiply two arbitrary precision integers. Certain applications require arbitraty precision arithmetic. One way to do this is to use arrays to represent integers with one digt per array entry. With the most significant digit appearing first, and a negative leading digit noting a negative integer

Write a program that takes two arrays representing integers and returns an integer representing their product.

As previously noted the possibilty of overflow precludes us from converting to the integer type. Instead we can use the grade school algorithm for multiplication which consists of multiplying the first number by the first digit add the terms rather than compute all of them then add them up. The number of digits required for the product is at most n+m for n digts and m digit operands

For example, when multiplying 123 x 987, we would form 7 x 123=861, then we would form 8 x 123 * 10=9840, which we would add to get 861 to get 10701 then we would form 9 x 123 x 100 = 110700 which we would add to the result to get 121401. 

All the numbers are represented as arrays

In [58]:
def determine_sign(digit1,digit2):
    if((digit1>0 and digit2>0) or (digit1<0 and digit2<0)):
        return 1
    else:
        return -1
    

#result len will dictate the number of leading zeros you want
def add_two_bit_arrays(arr1,arr2,result_len):
    if(result_len<(max(len(arr1),len(arr2))+1)):
        return "Not correct result len"
    else:
        result=[0]*result_len
        arr1_len=len(arr1)
        arr2_len=len(arr2)
        index=max(arr2_len,arr1_len,result_len)-1
        larger_index=max(arr2_len,arr1_len)-1
        carry=0
        for i in range(-1,-min(len(arr1),len(arr2))-1,-1):
            arr1_curr=arr1[i]
            arr2_curr=arr2[i]
            sum1=str(arr1_curr+arr2_curr+carry)
            if(len(sum1)==1):
                carry=0
                result[i]=int(sum1[0])
            else:
                carry=int(sum1[0])
                result[i]=int(sum1[1])
            index-=1 
            larger_index-=1
        print(index,carry)
        #now continue carring but with the larger arr
        if(arr1_len>arr2_len):
            longer_arr=arr1
        elif(arr1_len==arr2_len):
            if(carry>0):
                result[index]=carry
                return result
            else:
                return result
        else:
            longer_arr=arr2
            
        #finish adding with the longer array
        print(result,carry,larger_index)
        while(larger_index>=0):
            sum1=str(longer_arr[larger_index]+carry)
            if(len(sum1)==1):
                carry=0
                result[larger_index]=int(sum1)
            else:
                carry=int(sum1[0])
                result[larger_index]=int(sum1[1])
            index-=1
            larger_index-=1
            
        if(carry>0):
            result[index]=carry
        else:
            return result
            
            

    



def multiply_two_bit_arrays(arr1,arr2):
    #determine if the number is negative or positive
    sign_multiplier=determine_sign(arr1[1],arr2[1])
    #the result will be a maximum of n+m elements
    answer=[0]*(len(arr1)+len(arr2))
    for i in range(len(arr1)):
        result=0
        mult=arr1[i]
        for j in range (len(arr2)):
            print(mult,'*',arr2[j])
    
    
    
    
    

In [59]:
#multiply_two_bit_arrays([1,2,3],[1,2])
add_two_bit_arrays([1,1,1],[9,9],4)

1 1
[0, 0, 1, 0] 1 0
2


[2, 0, 1, 0]

In [20]:
test1=[3,2,1]
for i in range(-1,-len(test1)-1,-1):
    print(test1[i])

1
2
3


In [43]:
max(1,2,3)

3